### ISSUE TITLE
Touch detection on laptop touchscreen

### ISSUE THREAD

**Issue by marcusasplund** [rbiggs/hyper-tap#2]
Excellent work, a slight mishap happened for me though.
Problem: touch not detected
Device: Chromebook Pixel 2015 (touchscreen)
Might perhaps occur in surface and other devices with touch support and not mobile.

I had a false positive from the user agent detection from 
`/mobile/img.test(navigator.userAgent)` in 
https://github.com/rbiggs/hyper-tap/blob/master/src/events.js#L124

Here is the actual code where it occurred:
EDIT: broken link
~~https://glitch.com/edit/#!/toothsome-leo~~ 

This is a tricky thing from a ux perspective; on my laptop with touch screen, i expect that touch and pointer events behave in the same way. And detecting is always a mess, atm i use to go with `'ontouchstart' in window || navigator.maxTouchPoints`, as it works for my device.

With aliases we loose one of the events; mouse or touch.

**Comment by rbiggs** [comment]
OK, I probably need to update those detectors. This was thrown together really quickly based on other, more complicated event/gesture support I had done for ChocolateChip-UI. Originally it had support for pointer events, etc. But since Windows Phone is basically non-existent, it dropped that. 
I have a lot of devices - 16 phones (Windows Phone, Android and iPhone) and 4 tablets, and two Macs and two touch PC laptops. But I don't have a Chromebook. :-| So I guess I'll have to go to Best Buy and pick one up to test. Since they're cheap, no biggie. I'll do that later to day and take a look at how to make this work.

**Comment by rbiggs** [comment]
OK, just made a big update of feature detection complete with support for normal pointer events. Let me know if that resolves your issues.

**Comment by marcusasplund** [comment]
Thanks, it detects touch support on my Pixel now and works as expected.
But the problem i would like to solve in a plugin like yours is support for both keyboard and touch events, together or in different places. 
Ideally a setup like  
`el.addEventListener('swipeleft', swipeLeftToRemove, false)`
could be triggered by a finger swipe or a cursor drag on a device that has both a mouse(-pad) and a touchscreen, such as an ipad with keyboard, surface etc.
On the other side, then i could as well grab hammer.js.
If i come up with something i might create a pull request. 
(I am not sure of any other Chromebooks than the Pixel with a touchscreen. The Pixel is discontinued now as well. Excellent computer, but not that cheap btw)

The original posted link to glitchr has been broken so i a post new one here for reference
https://github.com/marcusasplund/hyperapp-todo/

**Comment by rbiggs** [comment]
I went out and bought a Samsung Chromebook like I said. It has a touch screen and a trackpad. But I wasn't sure what I was supposed to be testing for in your previous link. Give me a day or so to do some testing with screen/trackpad combos so I can see how that works. I used to have this stuff working with screen and trackpad on my Dell XPS 13, which has trackpad and touch screen, but that was with pointer events. Of course, you could use HammerJS, it's only 45kb minified :-\ Goes against the whole point of Hyperapp. I'm in the middle of debugging another project today, so hopefully I'll have some time tomorrow to deal with the Chromebook issue.

**Comment by rbiggs** [comment]
By the way, last thing I heard HammerJS had a lot of problems dealing with Android events. I know the pain. It's been 6 years of blood and sweat for me too. The mobile Chrome team are constantly screwing Web developers trying to implement gestures on that platform. They keep arbitrarily changing how events in mobile Chrome work - sometimes exposing things, then arbitrarily deciding that we don't need them :-( Really, really, really annoying. For example, they let you know when a touch.move starts, but not when it ends. WTF?!?  The reason they gave developers after we complained loudly on their forum was that why did we even need to have touch gestures on mobile. The real reason they took that away was so they could track swipes on mobile Chrome for history navigation. So, this may not be so easy. 
At least on the Window 8/10 touch laptops, when you touch the keyboard or the screen, the system switches to a different mode that you can test for so you can always get the gestures you expect while switching between trackpad and screen.

**Comment by rbiggs** [comment]
So, I just did some testing on my Dell and it wasn't doing the switching I was expecting there :-(. So I have some debugging to do. This will probably take a few days. Just so you know.

**Comment by marcusasplund** [comment]
Yeah, i am really attracted with hyperapps tiny footprint, thats why i was looking for some minimalistic lib that can fulfill basic needs. Hammer is actually around 20kb/7kb gzipped nowadays, but anyway it means a util 20x bigger than the framework itself. And i too have experienced all those problems with gestures on all kinds of platforms/devices/browsers, i know it's a pain :-(

**Comment by rbiggs** [comment]
Yup, I started out developing gestures back in '07 when the iPhone launched. It's been a long and difficult journey getting them to work consistently across platforms. I'll be working on this tomorrow. After I get to kick the tires a bit I'll post an update here. In my other framework, ChocolateChip-UI I don't have this problem. However, the events are tied up with a bunch of other stuff in the framework that shield some of the issues causing this, I think.

**Comment by rbiggs** [comment]
Just an update about gestures on touch devices. Anything involving Chrome browser and touch interfaces--Chromebooks, Android devices, Chrome desktop browser on Windows touchscreens--do not support touch gestures. That's right. This has been a long, heated debate between the Chrome team and mobile web developers for years. The Chrome team does not allow us to use long taps or swipe gestures when these are initiated by touch. When they're done with a mouse, no problem. The reason, the touch swipe gestures are used by Chrome to history navigation and the touch long tap is used to popup a context menu. Interestingly, the same gestures made with a mouse does not trigger these. 

This is their prerogative and they are not inclined to give developers access to these gestures on Chrome with touch screens. Whatever their reasoning, we are not able to use these with Chrome on a touch screen. All we can do is a tap.
